Hashtable hw
lyubortk/HSE-java-HW pull request #1
Opened 2019-01-21 03:58 UTC by lyubortk

2019-01-27 16:25 UTC, jzuken requested changes

2019-01-27 16:25 UTC, jzuken commented on hashtable/src/main/java/ru/hse/lyubortk/hashtable/Hashtable.java
> +        arr = new MyList[buckets];
лучше не использовать сокращений, да и в целом неудачное имя

2019-01-27 16:25 UTC, jzuken commented on hashtable/src/main/java/ru/hse/lyubortk/hashtable/Hashtable.java
> +        Iterator it = arr[bucket].iterator();
лучше уж тогда просто написать цикл for, который по итератору бегает

2019-01-27 16:25 UTC, jzuken commented on hashtable/src/main/java/ru/hse/lyubortk/hashtable/Hashtable.java
> +            var newHashtable = new Hashtable(bucketsNumber*2);
пробелов не хватает

2019-01-27 16:25 UTC, jzuken commented on hashtable/src/main/java/ru/hse/lyubortk/hashtable/Hashtable.java
> +        int hashCode = key.hashCode() % bucketsNumber;
hashCode() может и отрицательное значение вернуть

2019-01-27 16:25 UTC, jzuken commented on hashtable/src/main/java/ru/hse/lyubortk/hashtable/Hashtable.java
> +    private MyList[] arr;
поля обычно помещают в начале класса, перед методами

2019-01-27 16:25 UTC, jzuken commented on hashtable/src/main/java/ru/hse/lyubortk/hashtable/MyList.java
> +        private ListNode next;
опять же, не стоит экономить на именах переменных

2019-02-02 21:32 UTC, lyubortk commented on hashtable/src/main/java/ru/hse/lyubortk/hashtable/Hashtable.java
> +        int hashCode = key.hashCode() % bucketsNumber;
Я в return проверял с помощью оператора ?:
Добавил вместо него обычный if

2019-02-13 14:56 UTC, merged