Cannon
lyubortk/HSE-java-HW pull request #12
Opened 2019-05-21 21:06 UTC by lyubortk

2019-05-30 21:26 UTC, RamSaw requested changes
@lyubortk все ок, только со стайлгайдом беда что-то.

2019-05-30 21:26 UTC, RamSaw commented on cannon/build.gradle
> +mainClassName = 'ru.hse.lyubortk.cannon.CannonGameGUI'
jar не запускается

2019-05-30 21:26 UTC, RamSaw commented on cannon/settings.gradle
> +rootProject.name = 'cannon'
очень крутая графика, особенно взрыв! :)

2019-05-30 21:26 UTC, RamSaw commented on cannon/src/main/java/ru/hse/lyubortk/cannon/Cannon.java
> +                double fraction = dist/distanceToNext;
пробел

2019-05-30 21:26 UTC, RamSaw commented on cannon/src/main/java/ru/hse/lyubortk/cannon/CannonGameCore.java
> +            gameOverListener = (string -> {});
какой-то странный Listener, давайте сделаем так, чтобы он сразу был разумным, а не инициализировался потом.

2019-05-30 21:26 UTC, RamSaw commented on cannon/src/main/java/ru/hse/lyubortk/cannon/CannonGameGUI.java
> +                        new Rotate(-towerAngle, 0, Cannon.TOWER_WIDTH/2.0));
пробелы

2019-05-30 21:26 UTC, RamSaw commented on cannon/src/main/java/ru/hse/lyubortk/cannon/CannonGameGUI.java
> +
зачем тут пустые строки

2019-05-30 21:26 UTC, RamSaw commented on cannon/src/main/java/ru/hse/lyubortk/cannon/ExplosionListener.java
> +                double progress = timeDeltaMillis / (double)DURATION_MILLIS;
пробел...

2019-06-05 03:26 UTC, lyubortk commented on cannon/src/main/java/ru/hse/lyubortk/cannon/CannonGameCore.java
> +            gameOverListener = (string -> {});
Он в этом месте инициализировался, чтобы в дальнейшем все время не делать 
if (gameOverListener != null).
(А зарнанее инициализировать нельзя, потому что этот listener мог пользователь поставить равным null)

Заменил на ифы и вынес в отдельные методы, чтобы поприличней выглядело.

2019-06-05 03:27 UTC, lyubortk commented
@RamSaw, исправил.

2019-06-05 09:59 UTC, RamSaw approved these changes
@lyubortk все ок.
@jzuken

2019-06-05 09:59 UTC, RamSaw commented on cannon/src/main/java/ru/hse/lyubortk/cannon/CannonGameCore.java
> +                gameOverListener.accept("You won");
Можно было бы тогда сделать метод acceptIfNotNull, но да ладно.

2019-06-06 08:04 UTC, merged

2019-06-09 10:44 UTC, lyubortk commented
@jzuken, 
Тимофей Александрович, а вы мне в табличку баллы не поставили.