Myjunit
lyubortk/HSE-java-HW pull request #14
Opened 2019-06-01 15:46 UTC by lyubortk

2019-06-07 17:18 UTC, jzuken requested changes

2019-06-07 17:18 UTC, jzuken commented on myjunit/src/main/java/ru/hse/lyubortk/myjunit/MyJUnitCore.java
> +        List<Method> beforeClassMethods = getAnnotatedMethods(classMethods, BeforeClass.class);
а вы никак походу не проверяете, что аннотаций может быть не большое одной
-0.5

2019-06-07 17:18 UTC, jzuken commented on myjunit/src/main/java/ru/hse/lyubortk/myjunit/MyJUnitCore.java
> +    private static boolean checkHasNoParameters(@NotNull List<Method> methods) {
я бы убрал check из имени, это бы лучше подошло методу, который возвращает boolean

2019-06-07 17:33 UTC, lyubortk commented on myjunit/src/main/java/ru/hse/lyubortk/myjunit/MyJUnitCore.java
> +        List<Method> beforeClassMethods = getAnnotatedMethods(classMethods, BeforeClass.class);
@jzuken, а почему это плохо? Этого ограничения нет в тексте задания и это ничего не ломает.
Также это работает в JUnit 5 (например, единственный метод в тестовом классе с аннотациями  @Before @After @Test действительно запускается 3 раза).

2019-06-07 19:38 UTC, jzuken commented on myjunit/src/main/java/ru/hse/lyubortk/myjunit/MyJUnitCore.java
> +        List<Method> beforeClassMethods = getAnnotatedMethods(classMethods, BeforeClass.class);
а, блин, я это в условии не написал. ок, замечание снимается

2019-06-09 09:05 UTC, RamSaw commented
@lyubortk а где ваш PR с FtpGUI?

2019-06-09 10:40 UTC, lyubortk commented
@jzuken,
Исправил.

2019-06-12 09:36 UTC, merged