Trie hw
lyubortk/HSE-java-HW pull request #2
Opened 2019-02-03 15:27 UTC by lyubortk

2019-02-08 17:26 UTC, RamSaw requested changes
@lyubortk, домашку проверил. Как пофиксите или напишите контраргументы (не стесняйтесь спорить аргументированно, я тоже могу ошибаться), упомяните меня через "@RamSaw". У меня, к сожалению, доступа к hwproj нет, поэтому так поступим. Но если увижу на hwproj, что Вы пофиксили, то тоже посмотрю.

2019-02-08 17:26 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +
Зачем тут пустая строчка?

2019-02-08 17:26 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +/** A data structure to store set of strings.
Комментарии многострочные пишутся так:
`/**`
` * data1`
` * data2`
` */`
Это касается и всех дальнейших комментариев.

2019-02-08 17:26 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +        size = 0;
Эту инициализацию можно сделать сразу же при объявлении полей.

2019-02-08 17:26 UTC, RamSaw commented on trie/build.gradle
> +}
Добавьте сюда:

> test {
    useJUnitPlatform()
}

А то у Вас тесты не запускаются вообще-то. А когда запустите, то увидите, что они падают:

> ru.hse.lyubortk.trie.TrieTest > containsNull() FAILED
    org.opentest4j.AssertionFailedError at TrieTest.java:102
        Caused by: java.lang.NullPointerException at TrieTest.java:102

> ru.hse.lyubortk.trie.TrieTest > addNull() FAILED
    org.opentest4j.AssertionFailedError at TrieTest.java:63
        Caused by: java.lang.NullPointerException at TrieTest.java:63

> ru.hse.lyubortk.trie.TrieTest > removeNull() FAILED
    org.opentest4j.AssertionFailedError at TrieTest.java:137
        Caused by: java.lang.NullPointerException at TrieTest.java:137

2019-02-08 17:26 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +                var newSon = new TrieNode(depth+1, this, c);
`depth+1` -> `depth + 1`

2019-02-08 17:26 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +public class Trie {
Выделите отдельный интерфейс Serializable и имплементируйте его здесь.

2019-02-08 17:26 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +        if (node.depth == prefix.length()) {
Используйте тернарный оператор, кода не так уж и много.

2019-02-08 17:26 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +        var dataOut = new DataOutputStream(out);
try with resource, ниже тоже.

2019-02-08 17:26 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +    private class TrieNode {
Добавьте static, так как TrieNode не нужен instance самого бора.

2019-02-08 17:26 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +        TrieNode(int depthVal, @Nullable TrieNode fatherRef, char symbolVal) {
`fatherRef` - в джаве все ссылки. Можно именовать аргументы также как и поля, просто в теле надо будет писать `this.depth = depth`

2019-02-08 17:26 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +
пустая строка. Пожалуйста, удалите все ненужные пустые строки.

2019-02-08 17:26 UTC, RamSaw commented on trie/src/test/java/ru/hse/lyubortk/trie/TrieTest.java
> +
пустая строка

2019-02-08 17:26 UTC, RamSaw commented on trie/src/test/java/ru/hse/lyubortk/trie/TrieTest.java
> +    private static String[] getDictionary(int size) {
Юнит-тесты должны быть детерминированы. Просто генерируйте набор строк, интересный для тестирования.

2019-02-08 17:26 UTC, RamSaw commented on trie/src/test/java/ru/hse/lyubortk/trie/TrieTest.java
> +        assertThrows(IllegalArgumentException.class, () -> trie.add(null));
Аннотации от джетов не кидают исключений. Далее тоже самое встречается.

2019-02-08 17:26 UTC, RamSaw commented on trie/src/test/java/ru/hse/lyubortk/trie/TrieTest.java
> +        assertEquals(1000, trie.size());
DICT_SIZE лучше вместо 1000.

2019-02-08 17:26 UTC, RamSaw commented on trie/src/test/java/ru/hse/lyubortk/trie/TrieTest.java
> +        assertEquals(DICT_SIZE, anotherTrie.size());
Перегрузите equals у бора и проверяйте в одну строчку.

2019-02-08 17:26 UTC, RamSaw commented on trie/src/test/java/ru/hse/lyubortk/trie/TrieTest.java
> +    void serializeFromEmptyTrie() {
Сделайте еще тесты на serialize и deserialize в отдельности, а не только что результута identity.

2019-02-13 20:44 UTC, lyubortk commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +        var dataOut = new DataOutputStream(out);
А есть ли смысл, если ничего с этими исключениями я все равно сделать не смогу?
Или это для того, чтобы  вручуню не закрывать поток?

2019-02-13 20:50 UTC, lyubortk commented on trie/src/test/java/ru/hse/lyubortk/trie/TrieTest.java
> +    private static String[] getDictionary(int size) {
А там у рандома фиксированный seed. И размер словаря тоже фиксированный. Поэтому набор строк всегда одинаковый.

2019-02-13 22:31 UTC, lyubortk commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +        var dataOut = new DataOutputStream(out);
Оказывается, если закрыть DataOutputStream, то он вместе с собой закроет и тот поток, который нам передали аргументом в метод. Но, наверное, закрывать поток, который нам передали извне, не очень хорошая идея, поэтому try with resources не подойдет.

2019-02-13 22:41 UTC, lyubortk commented
@RamSaw, исправил все, кроме try-with-resources и словаря с рандомом. А эти два момента прокомментировал выше.

2019-02-17 21:21 UTC, RamSaw requested changes
Исправления посмотрел, с контраргументами согласен. Но появились новые замечания, жду исправлений.

2019-02-17 21:21 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +        var dataOut = new DataOutputStream(out);
Ок, согласен, my bad.

2019-02-17 21:21 UTC, RamSaw commented on trie/src/test/java/ru/hse/lyubortk/trie/TrieTest.java
> +        var serializationResult = new ByteArrayOutputStream();
А вот тут как раз тогда и нужен try with resources. В тестах ниже тоже добавьте, пожалуйста.

2019-02-17 21:21 UTC, RamSaw commented on trie/src/test/java/ru/hse/lyubortk/trie/TrieTest.java
> +                word[j] = (char) generator.nextInt(Character.MAX_VALUE);
ок, раз всегда одно и тоже. Но я бы не злоупотреблял такими тестами, потому что представьте, что у вас упал тест и ошибка нетривиальная. Мне кажется довольно трудно будет быстро понять почему он упал, так как у вас словарь очень большой. Но плюсы конечно в нем тоже есть, хоть это уже не очень похоже на юнит-тесты.

2019-02-17 21:21 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +    public boolean equals(Object o) {
equals и hashCode можно генерировать с помощью Идеи, понижает вероятность ошибиться и вообще удобно.

2019-02-17 21:21 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +        return (size == anotherTrie.size) && equalsSubtrees(root, anotherTrie.root);
Вот допустим здесь лучше было бы вызвать root.equals(anotherTrie.root).

2019-02-17 21:21 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +        return size;
По-моему такой hashCode очень плох. У Вас будут одинаковыми деревья просто с одним и тем же size. Вообщем-то поэтому я Вам посоветовал генерить Идеей.

2019-02-17 21:21 UTC, RamSaw commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +    private boolean equalsSubtrees(@Nullable TrieNode first, @Nullable TrieNode second) {
как-то очень сложно. Допустим у HashMap equals уже есть, его и надо вызывать. Давайте Вы все же сделаете (или нагенерите) equals и hashCode у TrieNode и Trie.

2019-02-24 20:51 UTC, lyubortk commented
@RamSaw, исправил.

2019-02-26 06:13 UTC, RamSaw approved these changes
Ok, передаю слово @jzuken

2019-03-07 10:57 UTC, jzuken requested changes

2019-03-07 10:57 UTC, jzuken commented on trie/src/main/java/ru/hse/lyubortk/trie/Serializable.java
> +     * @param out non-null {@link OutputStream} to write object state to
исключения тоже бы хорошо документировать

2019-03-07 10:57 UTC, jzuken commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +        } else {
а тут else можно не писать

2019-03-07 10:57 UTC, jzuken commented on trie/src/main/java/ru/hse/lyubortk/trie/Trie.java
> +        var curNode = root;
не используйте, пожалуйста, таких сокращений в коде
-0.5

2019-03-08 20:08 UTC, lyubortk commented
Исправил.
А почему в табличке -1.5 стоит, если вы только про -0.5 написали?

2019-03-09 21:11 UTC, RamSaw commented
> Исправил.
> А почему в табличке -1.5 стоит, если вы только про -0.5 написали?

@lyubortk у Вас юнит-тесты не запускались. Прошу прощения, что не сразу сказал об этом.

2019-03-09 21:17 UTC, lyubortk commented
@RamSaw, понял, спасибо.

2019-03-13 14:18 UTC, merged